# Default values for sample-service
replicaCount: 2

image:
  repository: sample-service
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

appmesh:
  enabled: true
  serviceName: sample-service
  virtualNode:
    listeners:
      - portMapping:
          port: 3000
          protocol: http
    backends: []

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/path: "/metrics"
  prometheus.io/port: "3000"

securityContext:
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000

nodeSelector: {}
tolerations: []
affinity: {}
